const MONTHS=[8,9,10,11,12,1,2];
const DEFAULTS=[
 {id:'major',name:'国有及主要股份行',keywords:'工商银行,建设银行,交通银行,邮储银行,邮政储蓄银行,国家开发银行,进出口银行,农业发展银行,广发银行,民生银行,兴业银行,光大银行,华夏银行,招商银行,浦发银行,上海浦东发展银行,平安银行',rates:{8:2.10,9:.60,10:.65,11:.65,12:.60,1:.57,2:.57},smallMin:1.90},
 {id:'big2',name:'中国银行、农业银行',keywords:'中国银行,农业银行',rates:{8:2.15,9:.65,10:.70,11:.70,12:.65,1:.60,2:.60}},
 {id:'city',name:'重点城商行',keywords:'江苏银行,北京银行,上海银行,宁波银行,浙商银行,南京银行',rates:{8:0,9:0,10:0,11:0,12:0,1:.60,2:.60}},
 {id:'other',name:'其他类银票',keywords:'',rates:{8:2.25,9:.75,10:.80,11:.80,12:.75,1:.70,2:.70}}
];
let rates=loadRates(),rows=[];
const $=id=>document.getElementById(id);
const money=new Intl.NumberFormat('zh-CN',{maximumFractionDigits:2});
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function loadRates(){try{return JSON.parse(localStorage.getItem('quote-rate-table-v1'))||structuredClone(DEFAULTS)}catch{return structuredClone(DEFAULTS)}}
function saveRates(){localStorage.setItem('quote-rate-table-v1',JSON.stringify(rates))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function formatDate(d){return d&&!isNaN(d)?d.toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}):'—'}
function excelDate(v){if(v instanceof Date)return new Date(v.getFullYear(),v.getMonth(),v.getDate());if(typeof v==='number'){const d=new Date(Math.round((v-25569)*86400000));return new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())}if(typeof v==='string'&&v.trim()){const d=new Date(v);if(!isNaN(d))return new Date(d.getFullYear(),d.getMonth(),d.getDate())}return null}
function classify(bank){for(const r of rates.filter(x=>x.id!=='other')){if(r.keywords.split(/[,，、\n]/).map(x=>x.trim()).filter(Boolean).some(k=>bank.includes(k)))return r}return rates.find(x=>x.id==='other')||rates[rates.length-1]}
function renderRates(){
 $('rateHead').innerHTML=`<tr><th>承兑行分类</th>${MONTHS.map(m=>`<th>${m}月</th>`).join('')}<th>银行匹配关键词</th></tr>`;
 $('rateBody').innerHTML=rates.map(r=>`<tr data-id="${r.id}"><td><strong>${esc(r.name)}</strong>${r.smallMin?`<small>100万以下参考下限 ${r.smallMin.toFixed(2)}</small>`:''}</td>${MONTHS.map(m=>`<td><input data-month="${m}" type="number" step="0.01" value="${r.rates[m]??''}" aria-label="${esc(r.name)}${m}月利率"></td>`).join('')}<td><textarea data-keywords aria-label="${esc(r.name)}匹配关键词" placeholder="${r.id==='other'?'默认分类，无需关键词':'用逗号分隔'}">${esc(r.keywords)}</textarea></td></tr>`).join('');
 document.querySelectorAll('[data-month]').forEach(el=>el.addEventListener('change',e=>{const id=e.target.closest('tr').dataset.id;rates.find(r=>r.id===id).rates[e.target.dataset.month]=Number(e.target.value);saveRates();recalc()}));
 document.querySelectorAll('[data-keywords]').forEach(el=>el.addEventListener('change',e=>{const id=e.target.closest('tr').dataset.id;rates.find(r=>r.id===id).keywords=e.target.value;saveRates();recalc()}));
}
function calculate(source){const discount=new Date($('discountDate').value+'T00:00:00');return source.map(row=>{const cat=classify(row.bank);const days=row.maturity?Math.round((row.maturity-discount)/86400000):null;const configured=row.maturity?cat.rates[row.maturity.getMonth()+1]:undefined;const rate=typeof configured==='number'?configured:null;const status=!row.maturity||!row.bank||!Number.isFinite(row.amount)||row.amount<=0||days===null||days<0?'error':rate===null||rate===0?'warn':'ok';return {...row,discount,days,rate,category:cat.name,status}})}
function recalc(){if(!rows.length)return;rows=calculate(rows);renderResults()}
function summary(){const valid=rows.filter(r=>r.status!=='error'&&r.days!==null&&r.rate!==null);const amount=valid.reduce((s,r)=>s+r.amount,0);const amountDays=valid.reduce((s,r)=>s+r.amount*r.days,0);return{valid:valid.length,issues:rows.length-valid.length,amount,days:amount?amountDays/amount:0,rate:amountDays?valid.reduce((s,r)=>s+r.amount*r.days*r.rate,0)/amountDays:0}}
function renderResults(){const s=summary();$('kpiDays').textContent=Math.round(s.days).toLocaleString('zh-CN');$('kpiAmount').textContent=money.format(s.amount);$('kpiRate').textContent=s.rate.toFixed(2);$('resultMeta').innerHTML=`<span>${s.valid} 条参与汇总</span>${s.issues?`<span class="issue">● ${s.issues} 条待检查</span>`:''}`;$('exportBtn').disabled=false;
 $('resultBody').innerHTML=rows.slice(0,150).map(r=>`<tr class="${r.status!=='ok'?'row-issue':''}"><td>${r.index}</td><td>${formatDate(r.maturity)}</td><td>${formatDate(r.discount)}</td><td>${r.days??'—'}</td><td>${r.rate===null?'未配置':r.rate.toFixed(2)+'%'}</td><td><span>${esc(r.bank||'未识别')}</span><small>${esc(r.category)}</small></td><td>${Number.isFinite(r.amount)?money.format(r.amount):'—'}</td><td><b class="badge ${r.status}">${r.status==='ok'?'正常':r.status==='warn'?'待确认':'异常'}</b></td></tr>`).join('');
 $('tableNote').textContent=rows.length>150?`网页仅预览前 150 条，导出的 Excel 包含全部 ${rows.length} 条。`:'';
}
async function readFile(file){if(!/\.xlsx?$/i.test(file.name)){setMessage('文件格式不支持，请上传 .xlsx 或 .xls 文件');return}setBusy(true,'正在读取并核对列名…');try{const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());const ws=wb.worksheets.find(s=>!/^sheet[12]$/i.test(s.name))||wb.worksheets[0];if(!ws)throw Error('工作簿中没有可读取的工作表');let header=0,cols={};for(let r=1;r<=Math.min(12,ws.rowCount);r++){ws.getRow(r).eachCell((cell,c)=>{const t=String(cell.text||'').replace(/\s/g,'');if(/^(金额|票面金额|票据金额)$/.test(t))cols.amount=c;if(/到期日|票据到期日/.test(t))cols.maturity=c;if(/银行名称|承兑行/.test(t))cols.bank=c});if(cols.amount&&cols.maturity&&cols.bank){header=r;break}}if(!header)throw Error('没有找到“金额、到期日、银行名称/承兑行”这三列');const parsed=[];for(let r=header+1;r<=ws.rowCount;r++){const av=ws.getCell(r,cols.amount).value,mv=ws.getCell(r,cols.maturity).value,bank=ws.getCell(r,cols.bank).text.trim();const amount=typeof av==='number'?av:Number(String(av??'').replace(/[,，￥¥\s]/g,''));if(!bank&&!mv&&!Number.isFinite(amount))continue;parsed.push({index:parsed.length+1,maturity:excelDate(mv),bank,amount})}rows=calculate(parsed);$('fileTitle').textContent=file.name;const issues=rows.filter(r=>r.status!=='ok').length;setMessage(`已读取 ${rows.length} 条票据${issues?`，其中 ${issues} 条需要检查`:'，全部匹配成功'}`);renderResults()}catch(e){rows=[];$('exportBtn').disabled=true;setMessage(e.message||'文件读取失败，请检查格式')}finally{setBusy(false)}}
function setMessage(t){$('message').textContent=t}function setBusy(b,t){$('dropzone').classList.toggle('busy',b);if(t)setMessage(t)}
async function exportExcel(){if(!rows.length)return;const s=summary(),wb=new ExcelJS.Workbook();wb.creator='票据报价测算工具';const rs=wb.addWorksheet('利率维护');rs.addRow(['承兑行分类',...MONTHS.map(m=>m+'月'),'匹配关键词','100万以下参考下限']);rates.forEach(r=>rs.addRow([r.name,...MONTHS.map(m=>r.rates[m]??null),r.keywords,r.smallMin??null]));rs.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};rs.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF173F35'}};rs.columns=[{width:25},...MONTHS.map(()=>({width:11})),{width:70},{width:20}];for(let c=2;c<=8;c++)rs.getColumn(c).numFmt='0.00';const ws=wb.addWorksheet('报价结果',{views:[{state:'frozen',ySplit:1}]});ws.addRow(['到期日','贴现日','计息天数','分行报价贴现利率','承兑行','金额','匹配分类','检查状态']);rows.forEach(r=>ws.addRow([r.maturity,r.discount,r.days,r.rate,r.bank,r.amount,r.category,r.status==='ok'?'正常':r.status==='warn'?'待确认':'异常']));ws.columns=[{width:14},{width:14},{width:12},{width:20},{width:48},{width:18},{width:24},{width:12}];ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF173F35'}};ws.getColumn(1).numFmt='yyyy/m/d';ws.getColumn(2).numFmt='yyyy/m/d';ws.getColumn(4).numFmt='0.00';ws.getColumn(6).numFmt='#,##0.00';ws.autoFilter={from:'A1',to:'H1'};ws.addRow([]);const start=ws.rowCount+1;[['加权平均天数',s.days],['合计金额',s.amount],['加权利率',s.rate]].forEach(x=>ws.addRow([null,null,null,null,null,x[0],x[1]]));for(let r=start;r<start+3;r++)for(let c=6;c<=7;c++){ws.getCell(r,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFFE36E'}};ws.getCell(r,c).font={bold:true}}ws.getCell(start,7).numFmt='0';ws.getCell(start+1,7).numFmt='#,##0.00';ws.getCell(start+2,7).numFmt='0.00';const blob=new Blob([await wb.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`报价测算结果_${$('discountDate').value}.xlsx`;a.click();URL.revokeObjectURL(url)}
$('discountDate').value=today();renderRates();$('discountDate').addEventListener('change',recalc);$('resetRates').addEventListener('click',()=>{rates=structuredClone(DEFAULTS);saveRates();renderRates();recalc()});$('exportBtn').addEventListener('click',exportExcel);const dz=$('dropzone'),fi=$('fileInput');dz.addEventListener('click',()=>fi.click());dz.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')fi.click()});dz.addEventListener('dragover',e=>{e.preventDefault();dz.classList.add('dragging')});dz.addEventListener('dragleave',()=>dz.classList.remove('dragging'));dz.addEventListener('drop',e=>{e.preventDefault();dz.classList.remove('dragging');if(e.dataTransfer.files[0])readFile(e.dataTransfer.files[0])});fi.addEventListener('change',()=>{if(fi.files[0])readFile(fi.files[0]);fi.value=''})
